# -*- coding: utf-8 -*-
"""Estudiantes1.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OJ12IiUB4L59IiQGnOzfoQR7tX825JuY
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

students=pd.read_csv('Students.csv')

students.head()

pd.unique(students['ID' ])

pd.unique(students['gender' ])

pd.unique(students['Algebra' ])

students['Algebra'].isna().sum()

students['Algebra'].mean()

students['Algebra']=students['Algebra'].fillna(students['Algebra'].mean())

students['Algebra'].isna().sum()

students.isna().sum()